### ISSUE TITLE
Link to model does not work

### ISSUE THREAD

**Issue by gremur** [kot-ne-kod-77/ru_punct#1]
Hello, the link mentioned in the README.md file does not work.

[Скачайте](https://drive.google.com/file/d/1ArzZuKFVyjriVYxKSHsOU5BKuSLVN1Ko/view?usp=sharing) модель из Google Drive и поместите в папку проекта. Запустите файл playing_with_model.py:

**Comment by gleb-skobinsky** [comment]
Hi!
Sorry about that, I updated the link and the readme file. Please use this link to download the tensorflow checkpoint: https://drive.google.com/file/d/1jHxW4D7O1V4-h-adJxW27QttYvlpC_w6/view?usp=sharing

**Comment by gremur** [comment]
Thank you!
